### ISSUE TITLE
Validate $APPS_JSON_BASE64 before building

### ISSUE THREAD

**Issue by juzerali** [frappe/frappe_docker#1093]
**Is your feature request related to a problem? Please describe.**
When trying to build docker image, if I make a mistake in generating the `$APPS_JSON_BASE64`, I get to know very late. First the entire python and nodejs dependencies are downloaded, only after that is the JSON validated. 

**Describe the solution you'd like**
If `APPS_JSON_BASE64` is invalid, fail the docker build process immediately. The feedback should take less than 5 seconds.

**Describe alternatives you've considered**
Just wait for the container to build for > 5 minutes before it fails.

**Additional context**

**Comment by revant** [comment]
send PR. 

`jq` is available in image at the point where apps.json is generated. Pipe the output through jq to validate json. accuracy of url and branch is not possible with jq.

https://github.com/frappe/frappe_docker/blob/26d7f37f23cdd747b3db3a9759f0611e9ee9916a/images/custom/Containerfile#L99-L99

**Comment by revant** [comment]
another alternative is to validate it externally.

I don't recommend adding it in image because validation is incomplete, it'll only check if json is valid. That is expected as you need to make sure you are using valid json before passing it as build arg

checking branch with or without auth is not going to happen during image building anyway. Bench init process does that validation and fails.
