### ISSUE TITLE
How to build custom image using an SSH key instead of a password?

### ISSUE THREAD

**Issue by azwalzaman** [frappe/frappe_docker#1101]
The instructions shown [here](https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md) show us how to use a repo with a password but what about with an SSH key? I ask this because Github deprecated support for password auth.
![image](https://user-images.githubusercontent.com/37041930/224969155-4534119e-7c10-45c5-bf88-14d1a81fad4b.png)

**Comment by revant** [comment]
Generate and use Access Tokens instead of passwords. That message will go away. Access tokens can have expiry, can be revoked or managed with more granular permissions on repository.

For SSH you'll have to write your own Dockerfile/Containerfile with ssh file copied or passed as env var, ssh agent and git configured to use ssh key. Search for "docker build git private clone"

Once git and ssh is working for the layer that does `bench init` with apps.json. It will clone using ssh instead of https.

**Comment by azwalzaman** [comment]
> Generate and use Access Tokens instead of passwords. That message will go away. Access tokens can have expiry, can be revoked or managed with more granular permissions on repository.
> 
> For SSH you'll have to write your own Dockerfile/Containerfile with ssh file copied or passed as env var, ssh agent and git configured to use ssh key. Search for "docker build git private clone"
> 
> Once git and ssh is working for the layer that does `bench init` with apps.json. It will clone using ssh instead of https.

Thanks for answering!
