### ISSUE TITLE
404 Page not found using Production Frappe Docer

### ISSUE THREAD

**Issue by mm86133** [frappe/frappe_docker#1127]
Used this copy & paste on ubuntu with docker

https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md

Up to this line **Create second bench**

**Comment by revant** [comment]
hope someone helps you, In use docker swarm or helm charts, can't help you with this as I don't use it.

**Comment by azwalzaman** [comment]
> 

I can help if you tell me the exact steps you followed

**Comment by mm86133** [comment]
> > 
> 
> I can help if you tell me the exact steps you followed. ie. example of how you entered the commands

Spun your test env with those steps copied to the script up to #Create a second bench line.#

I already wrote that I've used exact commands from that link.

**Comment by mm86133** [comment]
> lready wrote that I've used exact commands from that link.

Aren't running automated tests for CICD? How can you approve PR without tests? (automated)

**Comment by azwalzaman** [comment]
@mm86133 Are the containers running? Did you point a domain to the site you made?

**Comment by abelhoula** [comment]
I am facing the same issue.
I was wondering if its related to TLS/traeifk config, I've removed the proxy/TLS part too but the problem is still there 
I think somehow something went wrong on the frontend container here are the logs I 've found 


`2023-05-12 10:08:23,057 DEBUG cd /home/frappe/frappe-bench && bench build
2023-05-12 10:08:23,164 INFO /usr/local/bin/bench build
2023-05-12 10:08:42,638 INFO Bench /home/frappe/frappe-bench initialized
2023-05-12 10:08:42,904 INFO /usr/local/bin/bench get-app --branch=v14.24.1 --resolve-deps erpnext https://github.com/frappe/erpnext
2023-05-12 10:08:43,179 LOG Getting erpnext
2023-05-12 10:08:43,179 DEBUG cd ./apps && git clone https://github.com/frappe/erpnext --branch v14.24.1 --depth 1 --origin upstream
2023-05-12 10:08:48,624 LOG Installing erpnext
2023-05-12 10:08:48,758 DEBUG cd /home/frappe/frappe-bench && /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/frappe/frappe-bench/apps/erpnext 
2023-05-12 10:09:22,330 DEBUG cd /home/frappe/frappe-bench/apps/erpnext && yarn install
2023-05-12 10:09:23,474 DEBUG bench build --app erpnext
2023-05-12 10:09:23,579 INFO /usr/local/bin/bench build --app erpnext
2023-05-12 10:09:30,116 WARNING restart failed: Couldn't find supervisorctl in PATH`

**Comment by abelhoula** [comment]
I can confirm that the site provided in the .env file was not bootstrapped in the frontend container so it's normal I got a 404 response (no HTML/assets ...).
## WORKAROUND
@mm86133 I was able to Install it through https://github.com/frappe/bench , but this will install a default site called site1.localhost 🤣🤣🤣 + sites you will provide to the script, so you need to change in compose file manually the traefik config (label [replace the site1.localhost by your site ) and restart the whole stack (down + up) then you will be able to reach out your site. 

![image](https://github.com/frappe/frappe_docker/assets/45313572/0a75a490-e762-4c0b-a8b0-d5103f9c2774)

**Comment by 1ubuntuuser** [comment]
I think this might need to be reopened? 
The following from _example-one.env_ seems to indicate that new sites will be automatically added to traefik. So far the only way I have been able to get sites in traefik is to add them to them to frontend > Labels of example-one.yaml manually.
```
# List of sites for letsencrypt certificates quoted with backtick (`) and separated by comma (,)
# More https://doc.traefik.io/traefik/routing/routers/#rule
# About acme https://doc.traefik.io/traefik/https/acme/#domain-definition
SITES=`one.example.com`
```

**Comment by 1ubuntuuser** [comment]
The error was mine, in the example code below I had mistakenly edited "erp.example.com" with my own url. This value must be left as is. Perhaps this is what others have done too.
`sed -i 's/SITES=`erp.example.com`/SITES=\`one.example.com\`,\`two.example.com\`/g' ~/gitops/erpnext-one.env`
