### ISSUE TITLE
Docker Swarm Support

### ISSUE THREAD

**Issue by chabad360** [frappe/frappe_docker#118]
In the current state, the `docker-compose-*.yml` files do not support Docker Swarm, is there any plan to solve that (I can help with that), or are we going to focus primarily on k8s?

**Comment by revant** [comment]
I'll love to try out swarm. So many things to do! stack/secrets/configs/volumes will be nice! People can use portainer.io or swarmpit.io like app to create and manage their ERPNext installations using cool GUI.

**Comment by revant** [comment]
used https://github.com/evertramos/docker-portainer-letsencrypt
instead of https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion and I managed to get it working with portainer

![bench-console-portainer](https://user-images.githubusercontent.com/1040161/76701959-f9a66200-66eb-11ea-8263-0e95265d7d6d.png)

**Comment by revant** [comment]
https://github.com/frappe/frappe_docker/wiki/Docker-Swarm

**Comment by ddavidebor** [comment]
Please avoid using the wiki to dump notes, instead write documentation.
It's hard and messy to do PR on the wiki.

Il giorno dom 22 mar 2020 alle ore 11:57 Revant Nandgaonkar <
notifications@github.com> ha scritto:
