### ISSUE TITLE
ARM64 build problem at docker compose up stage

### ISSUE THREAD

**Issue by EmmanuelLM** [frappe/frappe_docker#1208]
Hi, I am trying to install erpnext docker on my ARM64 server.
I searched the documentation and issues on here but getting a bit stuck.
This is what I do:

```
git clone https://github.com/frappe/frappe_docker
cd frappe_docker
docker buildx bake --no-cache --set *.platform=linux/arm64
```

Up to here, it works successfully.

If I then do:
`docker compose -f ./pwd.yml up`

it fails with:
`no matching manifest for linux/arm64/v8 in the manifest list entries`

I saw someone had suggested adding "platform: linux/arm64" in the pwd.yml services but this produces the same error.

Any hints?

**Comment by revant** [comment]
edit the `docker-bake.hcl` file. Change image tag and version as per your build.

**Comment by EmmanuelLM** [comment]
this seems to work better (I have a version running!)... however, how can I target a specific version e.g. v14.35 - in pwd.yml that's straight forward but in docker-bake.hcl the tag is not recognised?

**Comment by revant** [comment]
> v14.35

There is no such version. It follows semver with vX.Y.Z

**Comment by EmmanuelLM** [comment]
Got it, thank you

**Comment by EmmanuelLM** [comment]
hmmm, trying to upgrade to v15 and struggling again to make it work, so any pointers would be appreciated....

Back to this:
1. `git clone https://github.com/frappe/frappe_docker
cd frappe_docker`
2. `export ERPNEXT_VERSION="version-15"` [I have tried using "15.0.0" here but this branch does not exist (the tag exists but not the branch and the git clone command fails)]
3. `docker buildx bake --no-cache --set *.platform=linux/arm64`
So far, so good
4. moved example.env to .env
5. saved pwd.yaml from the website and then issue:  `docker compose -f ./pwd.yaml pull`
I then get the error: "no matching manifest for linux/arm64/v8 in the manifest list entries"

I *think* the issue is in between the "version-15" branch, which compiles fine and the "v15.0.0", which is the actual branch but then does not compile....

**Comment by 1001Zebras** [comment]
Hi, I realize that this topic has been closed, and I'm entirely as to what the protocol is for this, but I figured I'd post here because my problem is near identical to the original one described. 
First, I've changed all mentions of "amd64" to "arm64" in the pwd.yml file, and run: 

``docker buildx bake --no-cache --set `*.platform=linux/arm64``

After running through a long string of processes and installs, it produces this error: 

``ERROR: failed to solve: process "/bin/sh -c bench init   --frappe-branch=${FRAPPE_BRANCH}   --frappe-path=${FRAPPE_PATH}   --no-procfile   --no-backups   --skip-redis-config-generation   --verbose   /home/frappe/frappe-bench &&   cd /home/frappe/frappe-bench &&   bench get-app --branch=${ERPNEXT_BRANCH} --resolve-deps erpnext ${ERPNEXT_REPO} &&   echo \"{}\" > sites/common_site_config.json &&   find apps -mindepth 1 -path \"*/.git\" | xargs rm -fr" did not complete successfully: exit code: 1``

Any ideas as to next steps?

Any and all help would be greatly appreciated. I've read through , I think most of the resources I can find through googling I've exhausted and I'm very stuck. 

Thank you, in advance.

**Comment by sharonpraju** [comment]
Run this command to build multi-architecture images specifically for ARM64.
`docker buildx bake --no-cache --set *.platform=linux/arm64`

and then 
- add `platform: linux/amd64` to all services in the `pwd.yaml`
- replace the current specified versions of erpnext image on `pwd.yml` with `:latest`

then run: `docker compose -f pwd.yml up -d`
