### ISSUE TITLE
Contribute to translation of erpnext

### ISSUE THREAD

**Issue by rvmadeit** [frappe/frappe_docker#1279]
Hi,

I just finished configure erpnext for my customer, but I want to translate it because it's a French company, so where can I translate for my customers, and can I also contribute to translate the entire app for you, for the French translation ?

**Comment by maxhboss** [comment]
same question here, installed using PWD.yml and cant seem to change language other than English.
Tried changing through System settings, but nothing seems to have changed.

**Comment by maxhboss** [comment]
nvm i just reinstalled and its working fine now,

**Comment by revant** [comment]
Check docs if they help or search forum

https://docs.erpnext.com/docs/v13/user/manual/en/translations

If you've multiple problems with docker don't install using docker, prefer native installation then you can open issues in respective repos instead of asking here on frappe_docker because you're using docker.
