### ISSUE TITLE
OperationalError pymysql.err.OperationalError

### ISSUE THREAD

**Issue by VPS010** [frappe/frappe_docker#1308]
Error:
OperationalError
pymysql.err.OperationalError: (1045, "Access denied for user '_aec0b9b259718551'@'172.22.0.2' (using password: YES)")

at:-  http://goalgrids.localhost:8000/
Site showing this error after restarting the bench.

**Comment by revant** [comment]
DO NOT miss --no-mariadb-socket while creating new-site.

https://github.com/frappe/frappe_docker/blob/main/docs/troubleshoot.md#fixing-mariadb-issues-after-rebuilding-the-container

**Comment by auliabismar** [comment]
> DO NOT miss --no-mariadb-socket while creating new-site.
> 
> https://github.com/frappe/frappe_docker/blob/main/docs/troubleshoot.md#fixing-mariadb-issues-after-rebuilding-the-container

in this doc, it suggest to change the host where user is  <db_name>. But there are no user record like <db-name> the only entries are: mariadb.sys, root, and healthcheck

Please advice.

**Comment by Benewend** [comment]
Hello i have been through this issue. I couldn't fix it i only had to work around. I understood that for me i had this issue because my password was containing a "#" then i tried the  setup using the "changeit" password and it worked fine. but now have problem with ssl ... for the record i use a ubuntu base vps ... hope i help someone
