### ISSUE TITLE
docker-compose commands

### ISSUE THREAD

**Issue by blaggacao** [frappe/frappe_docker#213]
https://docs.docker.com/compose/env-file/

> Compose supports declaring default environment variables in an environment file named .env placed in the folder where the docker-compose command is executed (current working directory).

This, among others renders:
```shell
docker-compose \
    --project-name testProject \
    -f installation/docker-compose-common.yml \
    -f installation/docker-compose-erpnext.yml \
    --project-directory installation up -d
```
invalid

given the readme says:
> To get started, copy the existing env-example file to .env inside the installation directory.

Maybe it really wants to say:
> To get started, copy the env-exampe file from the installation directory into the root directory as .env

But maybe that confilgts with `.devimages/...`

**Comment by revant** [comment]
I keep my .env where I execute docker-compose.

I changed it to current location because of this discussion. 
https://github.com/frappe/frappe_docker/pull/84#discussion_r386153591
It worked and I kept it there.

> https://docs.docker.com/compose/env-file/
> > Compose supports declaring default environment variables in an environment file named .env placed in the folder where the docker-compose command is executed (current working directory).

Please send PR. I'll merge the PR.

> But maybe that conflicts with .devimages/...

It won't conflict. Development docker-compose.yml doesn't take any variables. Even the mariadb root password is set to `123`.

As Alternative/Fix, It can even share common .env file.
Development will only need MYSQL_ROOT_PASSWORD

**Comment by blaggacao** [comment]
I'll do a PR, thanks!

**Comment by revant** [comment]
@blaggacao please review this https://github.com/frappe/frappe_docker/pull/216. Moving discussion there
