### ISSUE TITLE
Expected value utf8mb4_unicode_ci, found value latin1_swedish_ci

### ISSUE THREAD

**Issue by iot-resister** [frappe/frappe_docker#303]
same issue. 
https://discuss.erpnext.com/t/error-while-running-bench-new-site-site1-local/55522

running locally with arch linux.

What's the difference between yours and all this one? ?

https://github.com/pipech/erpnext-docker-debian/wiki/Trial-Setup

**Comment by revant** [comment]
I'm not able to reproduce this issue on my machine. Arch Linux.

Can you share the steps and logs?

**Comment by revant** [comment]
Reopen if needed.

**Comment by MrMauro** [comment]
Hi:
I'm having this issue in **Debian GNU/Linux 10 (buster)** whose locale reports:

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

I have selected the env **env-local** to build the **Development** and followed the instructions.

After noticing the **frappe_docker_site-creator_1** container halts, I've inspected its log which reported:

`Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 3 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _ca36d1ac5c42b512
Created database _ca36d1ac5c42b512
Granted privileges to user _ca36d1ac5c42b512 and database _ca36d1ac5c42b512
For key character_set_server. Expected value utf8mb4, found value latin1
For key collation_server. Expected value utf8mb4_unicode_ci, found value latin1_swedish_ci
================================================================================
Creation of your site - ra.local failed because MariaDB is not properly 
configured.  If using version 10.2.x or earlier, make sure you use the 
the Barracuda storage engine. 
Please verify the settings above in MariaDB's my.cnf.  Restart MariaDB.  And 
then run `bench new-site ra.local` again.
================================================================================
Database settings do not match expected values; stopping database setup.`

I've checked every MariaDB configuration file in search of those. Found that the mariadb 10.3 image this created had:
1) **character-set-server** instead of  **character_set_server**. Also goes the same for **collation_server** and **character_set_client_handshake**
2) /etc/mysql/mariadb.conf.d/50-server.cnf also had references to it.

I've tried this in an unsuccessful effort to solve that:

1) Replaced the - for _ on the tags on the **frappe.cnf** file on the host.
2) Inserted a line **./installation/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf** on the **docker-compose.yml** creating the file **50-server.cnf** file on the host at the installation folder with the desired content. 
3) Tried  **mariadb 10.5** instead **10.3** on replacing its tag on the **docker-compose.yml**
4) Checked https://github.com/pipech/erpnext-docker-debian/wiki/Trial-Setup that @iot-resister mentioned on their original post.

Thank you for any pointers.

**Comment by MrMauro** [comment]
I've managed to solve the original issue:
According to the [official documentation of the MariaDB Docker ](https://hub.docker.com/_/mariadb) those variables can be set on the docker-compose using this line on the MariaDB container definition:

`command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']`

No need to do anything like I mentioned on my previous post.

**Comment by revant** [comment]
command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--skip-character-set-client-handshake']

there is a config file that needs to be used

https://github.com/frappe/frappe_docker/blob/develop/installation/frappe-mariadb.cnf

https://github.com/frappe/frappe_docker/blob/develop/docker-compose.yml#L140

**Comment by MrMauro** [comment]
I've used it. It is actually called by **docker-compose.yml** by default, isn' it? 
And even I checked its content from the mariadb container issuing a cat to **/etc/mysql/conf.d/frappe.cnf**, which reported its content correctly so it wasn't a matter of file handling between the host and the container. But somehow the mariadb database does not takes that configuration. I've seen several post (many old) about this issue.
Calling the command proposed on the official documentation would make that easier, in my opinion.

**Comment by revant** [comment]
I just cloned fresh frappe_docker

cd frappe_docker
cp env-local .env
docker-compose up -d

It worked.

<details>

```
❯ cp env-local .env
❯ docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "frappe_docker_default" with the default driver
Creating volume "frappe_docker_mariadb-vol" with default driver
Creating volume "frappe_docker_redis-cache-vol" with default driver
Creating volume "frappe_docker_redis-queue-vol" with default driver
Creating volume "frappe_docker_redis-socketio-vol" with default driver
Creating volume "frappe_docker_assets-vol" with default driver
Creating volume "frappe_docker_sites-vol" with default driver
Creating volume "frappe_docker_cert-vol" with default driver
Pulling erpnext-nginx (frappe/erpnext-nginx:edge)...
^CGracefully stopping... (press Ctrl+C again to force)
❯ docker-compose up -d
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Pulling erpnext-nginx (frappe/erpnext-nginx:edge)...
edge: Pulling from frappe/erpnext-nginx
bf5952930446: Pull complete
cb9a6de05e5a: Pull complete
9513ea0afb93: Pull complete
b49ea07d2e93: Pull complete
a5e4a503d449: Pull complete
9a180c51b622: Pull complete
22e1af0cbf92: Pull complete
577b9ac99136: Pull complete
0b2b6610a5fd: Pull complete
9a886f19a840: Pull complete
54c6a766cb21: Pull complete
efa29ca911c3: Pull complete
f82c6977d346: Pull complete
Digest: sha256:e7f51805765ca33cb66c316d48421e23baf57350a83d29f94aa94bb2e2bae411
Status: Downloaded newer image for frappe/erpnext-nginx:edge
Pulling erpnext-python (frappe/erpnext-worker:edge)...
edge: Pulling from frappe/erpnext-worker
522a7372a4ae: Already exists
4dc0e6053004: Pull complete
1177fd529fce: Pull complete
f4cf1b5d54f9: Pull complete
0e5ba36f4507: Pull complete
e807f19f820d: Pull complete
c5fcf1a7d9fe: Pull complete
695656cdd17c: Pull complete
d19f1ebf123d: Pull complete
26fdce651e9c: Pull complete
3f2f0e5aca2e: Pull complete
629905ba7a18: Pull complete
9e68169d2053: Pull complete
ffe5cf60ce2c: Pull complete
51ff0ebc74a7: Pull complete
ccf23255cf45: Pull complete
016c4fe9efb5: Pull complete
b329928dfba0: Pull complete
ec873c783864: Pull complete
c8cea246e9be: Pull complete
36d3a7d8d973: Pull complete
Digest: sha256:a6b30d09b2face73b7997684be270d59b4335a34fbe01b44070034951d3634bd
Status: Downloaded newer image for frappe/erpnext-worker:edge
Pulling frappe-socketio (frappe/frappe-socketio:edge)...
edge: Pulling from frappe/frappe-socketio
75cb2ebf3b3c: Pull complete
1c6bd282486b: Pull complete
82de372909de: Pull complete
f1c229111278: Pull complete
2d6a826aec8f: Pull complete
113da50072f5: Pull complete
1a40529be776: Pull complete
a59be710122c: Pull complete
e10125c5a692: Pull complete
aea5cf310ccb: Pull complete
475ecc21e60f: Pull complete
c4220b215378: Pull complete
Digest: sha256:6d4b01a54ccc6eeff7a5cdaf2bcc0bb4eac36ce2c8b59f1d19a739d2c89538ca
Status: Downloaded newer image for frappe/frappe-socketio:edge
Creating frappe_docker_redis-socketio_1         ... done
Creating frappe_docker_mariadb_1        ... done
Creating frappe_docker_erpnext-nginx_1  ... done
Creating frappe_docker_traefik_1        ... done
Creating frappe_docker_redis-cache_1    ... done
Creating frappe_docker_redis-queue_1    ... done
Creating frappe_docker_erpnext-python_1 ... done
Creating frappe_docker_site-creator_1           ... done
Creating frappe_docker_erpnext-worker-short_1   ... done
Creating frappe_docker_erpnext-worker-default_1 ... done
Creating frappe_docker_erpnext-worker-long_1    ... done
Creating frappe_docker_erpnext-schedule_1       ... done
Creating frappe_docker_frappe-socketio_1        ... done
❯ docker logs frappe_docker_site-creator_1 -f
Attempt 1 to connect to mariadb:3306
Attempt 2 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Created user _69928f0f6369849a
Created database _69928f0f6369849a
Granted privileges to user _69928f0f6369849a and database _69928f0f6369849a
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***
❯ curl http://mysite.localhost | w3m -T text/html -dump
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18750    0 18750    0     0  76219      0 --:--:-- --:--:-- --:--:-- 76219
Home

  • Cart
  • Login

Javascript is disabled on your browser

You need to enable JavaScript for your app to work.
To enable it follow the instructions in the following link:
enable-javascript.com

[                    ]
[                    ] Show
Login
Don't have an account? Sign up

Forgot Password?

[                    ] [                    ] Sign up
Have an account? Login
[                    ] Reset Password
Back to Login
[                    ]
Get Updates
Powered by ERPNext - Open Source ERP Software
```

</details>

Last cron job tests passed

https://travis-ci.com/github/frappe/frappe_docker/jobs/372516981

**Comment by AbdelilahDerfoufi** [comment]
@revant Hello, I followed your footsteps and this is what I got

![image](https://user-images.githubusercontent.com/49759161/91020492-6c483180-e5ea-11ea-9f31-089187e2c4cf.png)

This is the list of containers

![image](https://user-images.githubusercontent.com/49759161/91020632-9e599380-e5ea-11ea-9f32-28e6d8915647.png)

**Comment by revant** [comment]
https://discuss.erpnext.com/t/404-not-found-on-port-change-docker/65019/10?u=revant_one

@AbdelilahDerfoufi no need of env-production in case of local setup. User env-local.

Also use traefik labels for further configuration if needed.

**Comment by AbdelilahDerfoufi** [comment]
@revant That's what I've been doing, and in case I need to switch to production, what can I do ?
