### ISSUE TITLE
Why cannot use bench inside docker console? 

### ISSUE THREAD

**Issue by perkasajob** [frappe/frappe_docker#315]
how to use bench command inside frappe_docker , need to make new-app ? 
with wiki info : _Bench Console and VS Code debugger_, but I haven't found launch.json configurations
and I tried "ln -s ~/frappe_docker/build/common/commands ~/frappe-bench/commands", but ~/frappe-bench/commands cannot be found

Thanks

**Comment by revant** [comment]
Are you using development setup or production setup?

- For production setup there is not bench installed. You need to make custom image for that. refer https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md

- For development setup bench command is available refer: https://github.com/frappe/frappe_docker/tree/develop/development

https://github.com/frappe/frappe_docker/wiki/Bench-Console-and-VS-Code-debugger This is for using debugger in bench console. e.g. you enter bench console and call some function, you can place breakpoints in code and even during executing the function in bench console, it will wait at breakpoint.

This is not part of launch json because sitename might change, blind copy-paste won't work.

**Comment by revant** [comment]
Reopen if needed.

**Comment by rupesh-techxcel** [comment]
@revant I installed erpnext with the pwd.yml file in the frappe docker. I am trying to restore the backup I have by entering to the docker container running with frontend (having port assigned). When I do bench restore it hangs after issuing mysql password. Nothing happens.
