### ISSUE TITLE
Could not find app "custom_app"

### ISSUE THREAD

**Issue by ahmadRagheb** [frappe/frappe_docker#389]
hi
i have follow the tutorial for single bench and how to add my custom app to it .
yet i allways get Could not find app "case_managment"

also i dropped db and created new one with same app still get the same issue 
Could not find app "case_managment", 
should i do something extra than in the docs ?

**Comment by revant** [comment]
for frappe to install and update apps on sites, it needs the app modules to be present in `apps.txt`.

Right now apps.txt is not updated everytime the container starts, it is only created if it is not present.

that means if new apps are added after install it will not be in apps.txt, you can manually add the app to apps.txt and try again.

**Comment by Sandah** [comment]
Reopening this because I had the same problem.
Could not find app "nextcloud-integration"
So as suggested on your answer revant I updated the apps.txt file ading nextcloud-integration to the list
but now I have another error 

ModuleNotFoundError: No module named 'nextcloud-integration'

What to do now ?

here is the full log from site-creator container : 

Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 45, in main
    frappe.init(site_name, new_site=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 195, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1077, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 943, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 901, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nextcloud-integration'

**Comment by revant** [comment]
app module should be named with underscore nextcloud_integration.

So even though the repo is nextcloud-integration, the local clone, app name and everything should be with underscore instead of hypen.

**Comment by Hadeer-Elsaeed** [comment]
@revant this also in deployment using docker ??

**Comment by revant** [comment]
Yes.

Py modules need to be named with underscore.

It applies everywhere, even in docker

**Comment by Sandah** [comment]
Hi @revant,

I tried everything that I could think of but I still have the same error message :
ModuleNotFoundError: No module named 'nextcloud_integration'

here is all the configuration for my last try with erpnext-shipping :

[apps.txt](https://github.com/frappe/frappe_docker/files/6004394/apps.txt)
[docker-compose-erpnext_shipping.yml.txt](https://github.com/frappe/frappe_docker/files/6004395/docker-compose-erpnext_shipping.yml.txt)
[Dockerfile_erpnext_shipping-nginx.txt](https://github.com/frappe/frappe_docker/files/6004396/Dockerfile_erpnext_shipping-nginx.txt)
[Dockerfile_erpnext_shipping-worker.txt](https://github.com/frappe/frappe_docker/files/6004397/Dockerfile_erpnext_shipping-worker.txt)
[env.txt](https://github.com/frappe/frappe_docker/files/6004398/env.txt)



logs site-creator container : 

Attempt 1 to connect to mariadb:3306
Attempt 1 to connect to redis-queue:6379
Attempt 1 to connect to redis-cache:6379
Attempt 1 to connect to redis-socketio:6379
Connections OK
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 109, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 45, in main
    frappe.init(site_name, new_site=True)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 195, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1077, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 943, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 901, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'erpnext_shipping'

help please ! 🙏

**Comment by saru2020** [comment]
i'm still facing this issue. 
i dont see the images for the custom app being built, basically the custom app itself is not fetched. 

how do i resolve this?

**Comment by saru2020** [comment]
raised a new defect(https://github.com/frappe/frappe_docker/issues/653) since i'm not able to reopen this one

**Comment by kalungia** [comment]
Hello I have been have this issue for 13 days has anybody been able to find a solution

**Comment by sdfateh** [comment]
@kalungia open a new ticket with details.
this issue related to old setup for frappe docker

**Comment by MohammedNoureldin** [comment]
Hi @sdfateh,

I also have the exact same issue. No more details needed actually, I just run ERPNext using Helm chart, and after installing any custom app, I cannot use ERPNext anymore, because of internal error, and the log shows, `module <custom app name> not found`.

**Comment by sherpa003** [comment]
having the same issue... with docker install, having development mode enabled, following the steps here: https://stackoverflow.com/questions/76206614/not-able-to-add-custom-app-in-frappe-docker

**Comment by AlaaL** [comment]
> app module should be named with underscore nextcloud_integration.
> 
> So even though the repo is nextcloud-integration, the local clone, app name and everything should be with underscore instead of hypen.

@revant you saved my day, that was the issue for me
