### ISSUE TITLE
frappe/erpnext-worker Dockerfile Source Code

### ISSUE THREAD

**Issue by alihalabyah** [frappe/frappe_docker#412]
Re https://github.com/frappe/frappe_docker/issues/411

@revant Thanks for your answer, I thought it's an old version as it has different commands than the recent bench and moreover you can't see what kind of version if you use `bench` version.

I don't need `bench` in production images, I had a few issues related to creating a new site, I was getting CSS not found issues whenever I try to navigate to the homepage but once I have executed the k8s job again to create the site with force option, the issue was resolved, this might be related to the fact that I have used the develop branch, not sure but I saw that you have once published develop, latest and some other tags altogether and that indicated all point to the same release, let me know please if that is false.

The Dockerfiles you have mentioned are the ones I was looking at and these don't have actual build instructions, instead, they are like black boxes, see https://github.com/frappe/frappe_docker/blob/develop/build/erpnext-worker/Dockerfile

Check FROM ${DOCKER_REGISTRY_PREFIX}/frappe-worker:${GIT_BRANCH} in this command we still need to rely on something we don't know, How can I built on top or extend ERPNext?

After all, thank you for the exceptional work!

**Comment by revant** [comment]
> @revant Thanks for your answer, I thought it's an old version as it has different commands than the recent bench and moreover you can't see what kind of version if you use `bench` version.

```shell
docker run --rm -it frappe/erpnext-worker:edge bench version
erpnext 13.x.x-develop
frappe 13.x.x-develop
```

It will show the version of apps installed in environment. It won't show bench version because bench is not installed.
There is NO bench to actually do framework commands. Important operations are in frappe framework itself, https://github.com/frappe/frappe/blob/develop/frappe/utils/bench_helper.py

> this might be related to the fact that I have used the develop branch, not sure but I saw that you have once published develop, latest and some other tags altogether and that indicated all point to the same release, let me know please if that is false.

- develop, edge and latest tags are pointing to develop branch of frappe DO NOT use in production.
- version-13-beta, v13, v13.0.0-beta.9 are version 13 beta
- version-12, v12, v12.16.2 are stable version 12
- version-11, v11, v11.1.0 are stable version 11

develop, edge and latest tags are NOT pointing to stable images.

> The Dockerfiles you have mentioned are the ones I was looking at and these don't have actual build instructions, instead, they are like black boxes, see https://github.com/frappe/frappe_docker/blob/develop/build/erpnext-worker/Dockerfile

- first frappe-worker images are made, https://github.com/frappe/frappe_docker/blob/develop/build/frappe-worker/Dockerfile
- frappe-worker image copies install_app.sh script https://github.com/frappe/frappe_docker/blob/develop/build/common/worker/install_app.sh and additional files
- erpnext-worker image takes frappe-worker image as base, it includes the scripts that make have the magic to build erpnext with one command.

> Check FROM ${DOCKER_REGISTRY_PREFIX}/frappe-worker:${GIT_BRANCH} in this command we still need to rely on something we don't know, How can I built on top or extend ERPNext?

We rely on frappe-worker image which is also made as part of this repo.
${DOCKER_REGISTRY_PREFIX} is used if you need to build and push on your own forks.

There is a link to https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md in README which can be used to build on top of erpnext-worker image.

**Comment by revant** [comment]
re-open if necessary
