### ISSUE TITLE
LDAP and SMTP/IMAP port mapping

### ISSUE THREAD

**Issue by mehmetalianil** [frappe/frappe_docker#624]
I installed and even migrated my old installation through SQL dumping. 
So, my question would be, now that docker compose ran successfully wrt the instructions, how can I enable ports required by the app for LDAP and mail? The container seems to fail in connecting those services in the localhost.

I think the instructions should make this case clear, since they are pretty standard features of an ERP system.

**Comment by revant** [comment]
the LDAP server is not installed in any containers.
you need to enter the host, ip or domain for any external service.

e.g. if you use Gmail, use smtp.gmail.com, for LDAP, setup your LDAP server separately and connect using ip/domain/hostname

**Comment by mehmetalianil** [comment]
Oh, I migrated a localhost instance to a docker instance. In the docker instance mail and LDAP ceased to work. 

I presumed that the container is unable to reach the ports of the host, and that is why. Wouldn't that be the case?

**Comment by revant** [comment]
If you need to access anything running on linux docker host use IP `172.17.0.1` instead of `localhost` or `127.0.0.1`.

There is no mail server or LDAP server packages installed in any of frappe/ERPNext container. You need to deploy LDAP and mail stacks/docker-compose separately and connect then through docker networking.

**Comment by mehmetalianil** [comment]
Thanks, 172.17.0.1 worked.
