### ISSUE TITLE
/files location is unreachable

### ISSUE THREAD

**Issue by revant** [frappe/frappe_docker#629]
Issue: https://discuss.erpnext.com/t/images-and-files-not-downloadable-in-the-docker-image/84485

Quick fix: https://discuss.erpnext.com/t/images-and-files-not-downloadable-in-the-docker-image/84485/4

Brief:

/files location in nginx config uses $http_host, changing it to $host solved the issue

@vrslev any idea?

**Comment by vrslev** [comment]
I'm not an expert in Nginx configuration. But I found this: https://stackoverflow.com/questions/15414810/whats-the-difference-of-host-and-http-host-in-nginx. Can this be relevant?

Also, title is a bit confusing 😅

**Comment by revant** [comment]
with $http_host it takes the port to try to reach the website and results into 404.

**Comment by vrslev** [comment]
Probably? 🤔

**Comment by revant** [comment]
as per #637 solution was discussed here https://github.com/frappe/erpnext/issues/28971#issue-1085277206

**Comment by revant** [comment]
@0FiRE0 can you try overriding custom file for now.

**Comment by 0FiRE0** [comment]
Thank you @revant for your response.
I have changed the nginx configuration file as per the below screenshot and the issue was resolved successfully. (changed `$http_host` to `$host` in the `/etc/nginx/conf.d/default.conf` file).

However, as soon as the container gets restarted, it reverts all the changes done in the configuration file, and I need to do it all over again.

![image](https://user-images.githubusercontent.com/19993814/149682929-7d25ec0c-73b7-4626-8f9c-1f9e9996f840.png)

**Comment by revant** [comment]
> Quick fix: https://discuss.erpnext.com/t/images-and-files-not-downloadable-in-the-docker-image/84485/4

follow this fix, here you override the full default.conf file by mounting it in container and set an environment variable.

**Comment by 0FiRE0** [comment]
Thank you @revant, it is working.

**Comment by vrslev** [comment]
@revant Can be closed?

**Comment by revant** [comment]
this is not commonly happening.
if it happens there is the solution.

things to note

1) the template location has changed after refactor
2) it is using upstream nginxinc/unprivileged template and can also pass env vars along with template.
