### ISSUE TITLE
How to upgrade frappe docker compose v13.21.0 to 13.22.x ?

### ISSUE THREAD

**Issue by xelfe** [frappe/frappe_docker#719]
Hello,
I'm looking for information on how to upgrade frappe docker v13.21.0 to v13.22.x? The docker file system is not the same anymore and no documentation mentions it.

best,

**Comment by revant** [comment]
yes, things have changed.

If you don't wish to change your existing yamls just use the compat branch of this repo. It has docker-compose.yml and additional env variables that make the new images work on previous yml. If you understand the yamls, you can refer that `docker-compose.yml` to make changes to any setups you've made anywhere else.

Option 1 (restore to new setup)

1. Add new compose/stack/helm chart with new images,
2. backup files and db from old compose/stack/helm chart
3. restore backup from old to new
4. Re wire traefik labels/ingress
5. Optionally delete old setup

Option 2 (Update and replace existing setup)

Instead of deleting old stack, update it. In case of compose you may have to `--remove-orphans`, In case of Helm Chart delete the resources and let `helm update` create new ones.

I have it setup on Kubernetes, I followed this to upgrade https://github.com/frappe/helm/tree/main/erpnext#migrate-from-helm-chart-3xx-to-4xx. It is the update and replace method.

**Comment by xelfe** [comment]
Alright so I'll go for the first option. I followed the instructions from the part "Setup ERPNext using containerized MariaDB and Redis with Letsencrypt certificates" but it seems that there are missing parameters about traefik. When I look at the proxy logs, I have the message "Domain name needs at least one dot" providerName=main-resolver.acme routerName=frontend-http@docker rule="Host(`frontend-electronic`)" .

**Comment by revant** [comment]
if you're not using docker swarm try the steps mentioned in this PR #715 

if they work, confirm on the PR and I'll merge it.

**Comment by revant** [comment]
open new or re-open if needed.

**Comment by miguelurtado** [comment]
Hello peoples...!

I installed ERPNext in Docker Swarm using this tutorial - https://github.com/frappe/frappe_docker/blob/compat/docs/docker-swarm.md

Even after updating ENVs, seted folder/volume assets and sites to uid:gid 1000:1000 this not work:

New ENVs in yml file.
```
  erpnext-nginx:
    environment:
      - BACKEND=erpnext-python:8000
      - SOCKETIO=frappe-socketio:9000
      - FRAPPE_SITE_NAME_HEADER=${FRAPPE_SITE_NAME_HEADER:-$host}
      - UPSTREAM_REAL_IP_ADDRESS=${UPSTREAM_REAL_IP_ADDRESS:-127.0.0.1}
      - UPSTREAM_REAL_IP_HEADER=${UPSTREAM_REAL_IP_HEADER:-X-Forwarded-For}
      - UPSTREAM_REAL_IP_RECURSIVE=${UPSTREAM_REAL_IP_RECURSIVE:-off}
```
 

Error on open erp.exemple.com/app/communication/XXXXXXXX
```FileNotFoundError: [Errno 2] No such file or directory: './assets/frappe/node_modules/ace-builds/src-min-noconflict/ace.js'```

Error on save custom site theme:
```
Error: Cannot find module 'node-sass'
Require stack:
- /home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at Object. (/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js:1:14)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/frappe/frappe-bench/apps/frappe/generate_bootstrap_theme.js'
]
}
```

Thanks frappe...!
