### ISSUE TITLE
Don't use `sudo`

### ISSUE THREAD

**Issue by alexanderadam** [frappe/frappe_docker#77]
[The Docker guide is very clear about user rights within a Container](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user):

> If a service can run without privileges, use USER to change to a non-root user.

because [having a user with `root` access is considered as dangerous](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b).

But for a reason that is unclear for me, [the `frappe` user is added to the `sudo` group](https://github.com/frappe/frappe_docker/blob/master/Dockerfile#L34-L35).

**Comment by chabad360** [comment]
Bench requires the frappe user to have sudo rights...

But I am working on discarding bench entirely, based on the work of [revant.one](https://gitlab.com/revant.one/erpnext_kubernetes)

> because having a user with root access is considered as dangerous .

This is due to Docker by default makes containers privileged, which means that `uid 1` and `gid 1` in the container get mapped to `uid 1` and `gid 1` on the host, which if turned off, will map the container root to something like `uid 10001` and `gid 10001`.

**Comment by alexanderadam** [comment]
Why is sudo needed at all? 🤔

**Comment by chabad360** [comment]
ask the guys who wrote bench (i.e. not me).



On 12/1/19, Alexander ADAM <notifications@github.com> wrote:
> Why is sudo needed at all? 🤔

>

> --

> You are receiving this because you commented.

> Reply to this email directly or view it on GitHub:

> https://github.com/frappe/frappe_docker/issues/77#issuecomment-560155275


-- 
Mendel G
chabad360@gmail.com

**Comment by chabad360** [comment]
Please close, since as of #84 this is no longer relevant.
