### ISSUE TITLE
ERPNext with Portainer and NGINX Proxy Manager

### ISSUE THREAD

**Issue by AizatHawari** [frappe/frappe_docker#785]
Hi, I need some advice from experts on this matter. I'm very new to this area and learning.

What I want to achieve is to have -  
1. Cockpit (as a GUI for the Linux server)  

2. Docker part: 

Portainer that has:
 - ERPNext (deploy ERPNext via Portainer) 
- Nginx Proxy Manager  

I wish to have Cockpit, Portainer and the rest use the Nginx proxy manager for the reverse proxy to ports 80 and 443.
What would be your advice for the ERPNext configurations on this current setup and any additional steps to make this Production ready?

**Comment by revant** [comment]
I used Google search,

I entered "cockpit linux" and found https://cockpit-project.org/documentation.html

I searched "nginx proxy manager and portainer" results in this video in English https://www.youtube.com/watch?v=TdEKVPWbC58, I'd recommend official documentation for each project instead of following any unofficial video.

Setting up cockpit for linux, portainer and nginx proxy manager is out of scope of this project.

To install ERPNext using docker compose, use this guide https://github.com/frappe/frappe_docker/blob/main/docs/single-server-example.md, If you understand docker, portainer and docker compose you'll be able to figure out the yaml needed to be applied to run the stack on portainer.

Recent thread about portainer stack : https://discuss.erpnext.com/t/erpnext-updating-from-13-22-1-to-13-25-1/88287/12

**Comment by agritheory** [comment]
I got this to work, but not in a Docker setup and I'm sorry only captured half of my process. I wanted to be able to have the URL be https://erp.mycompany.com/cockpit (without a port)
https://gist.github.com/agritheory/99ab1c09349ff314237919b03d843f19
