### ISSUE TITLE
Erpnext installation instructions are not clear, no one told me what the login mailbox is

### ISSUE THREAD

**Issue by zouzhe1** [frappe/frappe_docker#875]
This erpnext installation documentation is simply rubbish!
Question 1, I want to use docker to install, and then I found https://github.com/frappe/erpnext, indicating that there is a PWD in it.
Login for the PWD site: (username: Administrator, password: admin) This password and username are not correct at all, so I registered a new docker account myself, and after logging in, a page pops up, and then during loading, after ready, there is A close, but cannot be clicked.
Finally, F5, manually 8080, can finally enter the page, but only let you enter the mailbox and password, not the user name and password at all? I don't know how to log in? What is the email address? What is the password?
<img width="766" alt="capture" src="https://user-images.githubusercontent.com/13077962/184076731-b53cb6ee-66ba-441a-8167-cb0248504fb9.PNG">
---
Also, your open source is here, https://github.com/frappe/erpnext
Then want to install using docker, let me come here https://github.com/frappe/frappe_docker
Then there are a bunch of keywords bench, frappe,
-----Your documentation is very unfriendly, not clear at all, not even the login information, what is the mailbox? You only said how to set the administrator password and database password, but I can't log in! ! ! The login page only needs an email address, not a username! ! ! ! I'm furious.

**Comment by revant** [comment]
I cannot help you much. I only contibute my free time here. If you see pwd.yml It has `--admin-password` mentioned in site creation command. It should be picked up from the command. The `Administrator` already exists when new site is created and the mentioned password is set because of the `--admin-password` option.

https://github.com/frappe/frappe_docker/blob/c615b1c4bbda4d753fed2114e63f137db2202541/pwd.yml#L57

Personally, I'd recommend don't use frappe/erpnext or frappe/frappe_docker if it is so frustrating and makes you furious. It doesn't matter to me if you use it or not. I'm not gaining or losing anything. I've not sold you anything. I just try to help others by sharing my containerized setup. I gain nothing out of this.

**Comment by zouzhe1** [comment]
I have entered the website。
# Question 1, 
when you log in, you are only prompted to fill in the email address, and it does not say that you can directly fill in the administrator there. This is misleading.
# Question 2,
 when you write documents, you come up with a bunch of unfamiliar keywords. You are from the perspective of your design, and you do not consider the problem from the perspective of document readers. Programmers have this kind of problem! People need to empathize. If you are a person who does not understand this thing, what will happen when you see this document? So I would say that your documentation is not well done, this is sincere advice.

**Comment by revant** [comment]
> when you log in, you are only prompted to fill in the email address, and it does not say that you can directly fill in the administrator there. This is misleading.

The login functionality is part of Frappe framework. Create an issue in Frappe framework's GitHub repository. Try to be polite when you create the issue.

> So I would say that your documentation is not well done, this is sincere advice.

Most of the people who use and contribute to this repo are devops or developers. So they make the documentation for their target audience.

beyond this repo many changes are made regularly that can be addressed in their respective repos/issues.

**Comment by abhishekbalam** [comment]
@zouzhe1 please be polite and respectful when raising issues here. Blind outrage and agitation on an opensource tool you use for free is just tasteless and terrible behaviour. 

Yes, there's some things we can improve on docs front but it's an opensource tool, you can contribute with a PR too if you 
 really can do things better (I'm doubtful, because [just look at this](https://github.com/zouzhe1/jetbot-4wd-drive)) but just rude outrage is not acceptable.

Repos like this are volunteer work and there needs to be empathy from your side too. Not to mention none of the issues you mentioned is related to this repo.

CC: @revant

**Comment by revant** [comment]
I'll close this.

Open issues in GitHub repos for Frappe, Bench or ERPNext

Documentation which is wiki you can edit it if you find any issues.

**Comment by Geowan** [comment]
A simple answer would suffice in this what is the login username and password when you use docker.
I have tried login with username Administrator and password admin and doesnt work. 
I understand its opensource but setup and login credentials should be available. 
Let not think about how the rest api documentation lacks information on alot of stuff.
