### ISSUE TITLE
How to connecting my web application to socket io in frappe (Docker local development) 

### ISSUE THREAD

**Issue by rully-saputra15** [frappe/frappe_docker#878]
## Description of the issue

So I want to connect my web application that was made from react to frappe. I have already installed the socket io client and connected it to the other socket io server. It was successful when I tried to connect socket io frappe(Docker local development). It always showed "Unable to join the chat room. ECONNREFUSED 127.0.0.1:3002". Is there any guide to testing socket io from local? I have already read this wiki https://github.com/frappe/frappe/wiki/How-to-setup-Socketio-for-development-mode

but it's not solving my problem.

[this is an error from socket io client](https://i.stack.imgur.com/XlLWR.png)

Please anyone help me, thank you in advance!

## Steps to reproduce the issue

1.
2.
3.

### Stacktrace / full error message if available

```
(paste here)
```

**Comment by revant** [comment]
socketio.js from frappe has a function `get_url()` it picks up header for origin.

in case of production instance it resolves correctly e.g. `erp.example.com/api/method/frappe.realtime.get_user_info`
in case of development or local setup it resolves to `something.localhost:8000/api/method/frappe.realtime.get_user_info`. In this case the container tries to connect to localhost instead of correct service with correct host header.

We can change the code of socketio.js with condition that checks developer_mode: 1 or is_localhost: 1 and make request to correct backend container with host header.

Can you confirm this locally?

**Comment by rully-saputra15** [comment]
Hello @revant , thank you for your solution but I have confused with condition that checks developer_mode. Could you give me the tutorial for changing it? because for now, I don't bypass any socketio code in frappe. thank you in advance!

**Comment by revant** [comment]
Simple fix for development setup is to add `extra_hosts` to the `frappe` container. Point the site names to `172.17.0.1` (container host ip)

e.g. `.devcontainer/docker-compose.yml` changes

```yaml
version: "3.7"
services:
  ...
  frappe:
    ...
    extra_hosts:
      - site1.localhost:172.17.0.1
      - site2.localhost:172.17.0.1
```
